### ISSUE TITLE
What software to use to simulate workloads

### ISSUE THREAD

**Issue by Jwinf** [WHU-AISE/PBScaler#1]
I read your paper PBScaler: A Bottleneck-aware Autoscaling Framework for Microservice-based Applications. I was impressed by your innovation and I am very interested. I would like to ask you what software you are using to simulate workflow loads.
I've acquired the Wikipedia workload from the Wiki-Pageviews, a GZ file. But I don't know how to use it. 
Thank you for your help.

**Comment by TVDiag** [comment]
> I read your paper PBScaler: A Bottleneck-aware Autoscaling Framework for Microservice-based Applications. I was impressed by your innovation and I am very interested. I would like to ask you what software you are using to simulate workflow loads. I've acquired the Wikipedia workload from the Wiki-Pageviews, a GZ file. But I don't know how to use it. Thank you for your help.

Sorry, I just saw this issue. I use [locust](https://docs.locust.io) to simulate workflow loads.

**Comment by theoryXie** [comment]
> I read your paper PBScaler: A Bottleneck-aware Autoscaling Framework for Microservice-based Applications. I was impressed by your innovation and I am very interested. I would like to ask you what software you are using to simulate workflow loads. I've acquired the Wikipedia workload from the Wiki-Pageviews, a GZ file. But I don't know how to use it. Thank you for your help.

Sorry, I just saw this issue. I use [locust](https://locust.io) to simulate workflow loads.
